#!/bin/bash

# Source EVM environment 
[ -f /etc/default/evm ] &&  . /etc/default/evm

# Check postgres server DB init status, if necessary, initdb, start/enable service and inject MIQ role
PGDATA=/var/lib/pgsql/data
PG_CHECK_DB=/usr/bin/postgresql-check-db-dir

if [ -x ${PG_CHECK_DB} ]; then

        echo "== Checking MIQ database status =="
        ${PG_CHECK_DB} ${PGDATA}
                if [ $? -eq 0 ]; then
                        systemctl is-active -q postgresql
                        if [ $? -ne 0 ]; then
                                echo "** Postgresql is inactive, starting service"
                                systemctl start postgresql
                                test $? -ne 0 && echo "!! Failed to start postgresql service" && exit 1
                                echo "** Postgresql is now online"
                        fi
                        psql --list | grep -q vmdb
                        test $? -ne 0 && echo "!! MIQ database could not be found, re-run ${BASEDIR}/bin/docker_setup?" && exit 1
                        echo "** MIQ vmdb was found"
                        exit 0
                else
                        echo "** DB has not been initialized"
                        echo "** Launching initdb"
                        su postgres -c "initdb -D ${PGDATA}"
                        test $? -ne 0 && echo "!! Failed to initdb" && exit 1
                        echo "** Starting postgresql"
                        systemctl start postgresql
                        test $? -ne 0 && echo "!! Failed to start postgresql service" && exit 1
                        echo "** Creating MIQ role"
                        su postgres -c "psql -c \"CREATE ROLE root SUPERUSER LOGIN PASSWORD 'smartvm'\""
                        test $? -ne 0 && echo "!! Failed to inject MIQ root Role" && exit 1
                        echo "** Starting DB setup"
                        ${BASEDIR}/bin/docker_setup
                        test $? -ne 0 && echo "!! ${BASEDIR}/bin/docker_setup failed to run" && exit 1
                        echo "** MIQ database has been initialized"
                        systemctl enable -q postgresql
                        exit 0
                fi
else
        echo "Failed to find ${PG_CHECK_DB}, is postgres server installed?"
        exit 1
fi
}
